package shared.functionality.network;

public enum RequestType {
	CLIENT_REQUEST_AUTHENTICATE_UDP,
	CLIENT_REQUEST_GAME_ACTION_CONTROL_SHIP,
	CLIENT_REQUEST_GAME_ACTION_SPAWN_SHIP,
	SERVER_REPONSE_UPDATE_ENTITIES,
	SERVER_REPONSE_SPAWN_ENTITIES,
	CLIENT_REQUEST_READY,
	CLIENT_REQUEST_PING;
	
	public byte asByte() {
		return (byte) this.ordinal();
	}
}
