package shared.functionality;

public enum EventType {
	// Client events
	CLIENT_EVENT_AUTHENTICATE,
	CLIENT_EVENT_SERVER_JOIN,
	CLIENT_EVENT_SERVER_CONNECT,
	CLIENT_EVENT_SERVER_DISCONNECT,
	CLIENT_EVENT_SERVER_FAILED_TO_CONNECT,
	CLIENT_EVENT_CREATE_UNIT,
	CLIENT_EVENT_UPDATE_UNIT,
	// Server events

}
