package shared.functionality;

public enum EventType {
	// Client events
	CLIENT_EVENT_AUTHENTICATE,
	CLIENT_EVENT_SERVER_JOIN,
	CLIENT_EVENT_SERVER_CONNECT,
	CLIENT_EVENT_SERVER_DISCONNECT,
	CLIENT_EVENT_SERVER_FAILED_TO_CONNECT,
	CLIENT_EVENT_SNAPSHOT_CREATE,
	CLIENT_EVENT_SNAPSHOT_UPDATE,
	CLIENT_EVENT_SNAPSHOT_END,
	CLIENT_EVENT_SPAWN_PLAYER_SHIP,
	CLIENT_EVENT_CREATE_ACCOUNT, CLIENT_EVENT_TOGGLE_MOUSE,
	// Server events

}
